package scard

// #cgo pkg-config: libpcsclite
// #include <winscard.h>
// #include <reader.h>
import "C"

const (
	ATTR_VENDOR_NAME              uint32 = C.SCARD_ATTR_VENDOR_NAME
	ATTR_VENDOR_IFD_TYPE          uint32 = C.SCARD_ATTR_VENDOR_IFD_TYPE
	ATTR_VENDOR_IFD_VERSION       uint32 = C.SCARD_ATTR_VENDOR_IFD_VERSION
	ATTR_VENDOR_IFD_SERIAL_NO     uint32 = C.SCARD_ATTR_VENDOR_IFD_SERIAL_NO
	ATTR_CHANNEL_ID               uint32 = C.SCARD_ATTR_CHANNEL_ID
	ATTR_ASYNC_PROTOCOL_TYPES     uint32 = C.SCARD_ATTR_ASYNC_PROTOCOL_TYPES
	ATTR_DEFAULT_CLK              uint32 = C.SCARD_ATTR_DEFAULT_CLK
	ATTR_MAX_CLK                  uint32 = C.SCARD_ATTR_MAX_CLK
	ATTR_DEFAULT_DATA_RATE        uint32 = C.SCARD_ATTR_DEFAULT_DATA_RATE
	ATTR_MAX_DATA_RATE            uint32 = C.SCARD_ATTR_MAX_DATA_RATE
	ATTR_MAX_IFSD                 uint32 = C.SCARD_ATTR_MAX_IFSD
	ATTR_SYNC_PROTOCOL_TYPES      uint32 = C.SCARD_ATTR_SYNC_PROTOCOL_TYPES
	ATTR_POWER_MGMT_SUPPORT       uint32 = C.SCARD_ATTR_POWER_MGMT_SUPPORT
	ATTR_USER_TO_CARD_AUTH_DEVICE uint32 = C.SCARD_ATTR_USER_TO_CARD_AUTH_DEVICE
	ATTR_USER_AUTH_INPUT_DEVICE   uint32 = C.SCARD_ATTR_USER_AUTH_INPUT_DEVICE
	ATTR_CHARACTERISTICS          uint32 = C.SCARD_ATTR_CHARACTERISTICS
	ATTR_CURRENT_PROTOCOL_TYPE    uint32 = C.SCARD_ATTR_CURRENT_PROTOCOL_TYPE
	ATTR_CURRENT_CLK              uint32 = C.SCARD_ATTR_CURRENT_CLK
	ATTR_CURRENT_F                uint32 = C.SCARD_ATTR_CURRENT_F
	ATTR_CURRENT_D                uint32 = C.SCARD_ATTR_CURRENT_D
	ATTR_CURRENT_N                uint32 = C.SCARD_ATTR_CURRENT_N
	ATTR_CURRENT_W                uint32 = C.SCARD_ATTR_CURRENT_W
	ATTR_CURRENT_IFSC             uint32 = C.SCARD_ATTR_CURRENT_IFSC
	ATTR_CURRENT_IFSD             uint32 = C.SCARD_ATTR_CURRENT_IFSD
	ATTR_CURRENT_BWT              uint32 = C.SCARD_ATTR_CURRENT_BWT
	ATTR_CURRENT_CWT              uint32 = C.SCARD_ATTR_CURRENT_CWT
	ATTR_CURRENT_EBC_ENCODING     uint32 = C.SCARD_ATTR_CURRENT_EBC_ENCODING
	ATTR_EXTENDED_BWT             uint32 = C.SCARD_ATTR_EXTENDED_BWT
	ATTR_ICC_PRESENCE             uint32 = C.SCARD_ATTR_ICC_PRESENCE
	ATTR_ICC_INTERFACE_STATUS     uint32 = C.SCARD_ATTR_ICC_INTERFACE_STATUS
	ATTR_CURRENT_IO_STATE         uint32 = C.SCARD_ATTR_CURRENT_IO_STATE
	ATTR_ATR_STRING               uint32 = C.SCARD_ATTR_ATR_STRING
	ATTR_ICC_TYPE_PER_ATR         uint32 = C.SCARD_ATTR_ICC_TYPE_PER_ATR
	ATTR_ESC_RESET                uint32 = C.SCARD_ATTR_ESC_RESET
	ATTR_ESC_CANCEL               uint32 = C.SCARD_ATTR_ESC_CANCEL
	ATTR_ESC_AUTHREQUEST          uint32 = C.SCARD_ATTR_ESC_AUTHREQUEST
	ATTR_MAXINPUT                 uint32 = C.SCARD_ATTR_MAXINPUT
	ATTR_DEVICE_UNIT              uint32 = C.SCARD_ATTR_DEVICE_UNIT
	ATTR_DEVICE_IN_USE            uint32 = C.SCARD_ATTR_DEVICE_IN_USE
	ATTR_DEVICE_FRIENDLY_NAME     uint32 = C.SCARD_ATTR_DEVICE_FRIENDLY_NAME
	ATTR_DEVICE_SYSTEM_NAME       uint32 = C.SCARD_ATTR_DEVICE_SYSTEM_NAME
	ATTR_SUPRESS_T1_IFS_REQUEST   uint32 = C.SCARD_ATTR_SUPRESS_T1_IFS_REQUEST
)
